# Form implementation generated from reading ui file 'd:\Python\Stock_py\Ui_File\pofo_data.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Portfolio_Data(object):
    def setupUi(self, Portfolio_Data):
        Portfolio_Data.setObjectName("Portfolio_Data")
        Portfolio_Data.resize(500, 630)
        Portfolio_Data.setMinimumSize(QtCore.QSize(500, 630))
        Portfolio_Data.setMaximumSize(QtCore.QSize(500, 630))
        Portfolio_Data.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"border-color: rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Portfolio_Data)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_lb = QtWidgets.QLabel(parent=Portfolio_Data)
        self.back_lb.setMinimumSize(QtCore.QSize(200, 25))
        self.back_lb.setMaximumSize(QtCore.QSize(100, 25))
        self.back_lb.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.back_lb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.back_lb.setObjectName("back_lb")
        self.horizontalLayout.addWidget(self.back_lb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backtestpofotableView = QtWidgets.QTableView(parent=Portfolio_Data)
        self.backtestpofotableView.setMaximumSize(QtCore.QSize(470, 16777215))
        self.backtestpofotableView.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"border-color: rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);")
        self.backtestpofotableView.setObjectName("backtestpofotableView")
        self.horizontalLayout_2.addWidget(self.backtestpofotableView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Backtest_Btn_enter = QtWidgets.QPushButton(parent=Portfolio_Data)
        self.Backtest_Btn_enter.setMinimumSize(QtCore.QSize(100, 25))
        self.Backtest_Btn_enter.setMaximumSize(QtCore.QSize(1000, 25))
        self.Backtest_Btn_enter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.Backtest_Btn_enter.setObjectName("Backtest_Btn_enter")
        self.horizontalLayout_4.addWidget(self.Backtest_Btn_enter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Portfolio_Data)
        QtCore.QMetaObject.connectSlotsByName(Portfolio_Data)

    def retranslateUi(self, Portfolio_Data):
        _translate = QtCore.QCoreApplication.translate
        Portfolio_Data.setWindowTitle(_translate("Portfolio_Data", "Portfolio For Analysis"))
        self.back_lb.setText(_translate("Portfolio_Data", "Backtest Portfolio"))
        self.Backtest_Btn_enter.setText(_translate("Portfolio_Data", " Enter to Quit the application"))
