# Form implementation generated from reading ui file 'd:\Python\Stock_py\Ui_File\companyOfficers.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CompanyOfficers(object):
    def setupUi(self, CompanyOfficers):
        CompanyOfficers.setObjectName("CompanyOfficers")
        CompanyOfficers.resize(919, 522)
        CompanyOfficers.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CompanyOfficers)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=CompanyOfficers)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setMaximumSize(QtCore.QSize(150, 25))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(150, 440, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_6.addItem(spacerItem)
        self.Btn_Exit = QtWidgets.QPushButton(parent=CompanyOfficers)
        self.Btn_Exit.setMaximumSize(QtCore.QSize(150, 23))
        self.Btn_Exit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.verticalLayout_6.addWidget(self.Btn_Exit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.officertableview = QtWidgets.QTableView(parent=CompanyOfficers)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.officertableview.setFont(font)
        self.officertableview.setStyleSheet("")
        self.officertableview.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.officertableview.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.officertableview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.officertableview.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.officertableview.setCornerButtonEnabled(False)
        self.officertableview.setObjectName("officertableview")
        self.horizontalLayout_4.addWidget(self.officertableview)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(CompanyOfficers)
        self.Btn_Exit.clicked.connect(CompanyOfficers.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CompanyOfficers)

    def retranslateUi(self, CompanyOfficers):
        _translate = QtCore.QCoreApplication.translate
        CompanyOfficers.setWindowTitle(_translate("CompanyOfficers", "Company Officers"))
        self.label_11.setText(_translate("CompanyOfficers", "Company Officers Detail"))
        self.Btn_Exit.setText(_translate("CompanyOfficers", "Exit"))
