# Form implementation generated from reading ui file 'd:\Python\Stock_py\Ui_File\longbussum.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_longbussum(object):
    def setupUi(self, longbussum):
        longbussum.setObjectName("longbussum")
        longbussum.resize(810, 290)
        longbussum.setMinimumSize(QtCore.QSize(810, 290))
        longbussum.setMaximumSize(QtCore.QSize(810, 290))
        longbussum.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"border-color: rgb(47, 47, 47);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(longbussum)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=longbussum)
        self.label_11.setMinimumSize(QtCore.QSize(150, 25))
        self.label_11.setMaximumSize(QtCore.QSize(150, 25))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(150, 208, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_6.addItem(spacerItem)
        self.Btn_Exit = QtWidgets.QPushButton(parent=longbussum)
        self.Btn_Exit.setMinimumSize(QtCore.QSize(150, 23))
        self.Btn_Exit.setMaximumSize(QtCore.QSize(150, 23))
        self.Btn_Exit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.verticalLayout_6.addWidget(self.Btn_Exit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.sum_edit = QtWidgets.QTextEdit(parent=longbussum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.sum_edit.setFont(font)
        self.sum_edit.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);")
        self.sum_edit.setReadOnly(True)
        self.sum_edit.setObjectName("sum_edit")
        self.horizontalLayout_4.addWidget(self.sum_edit)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(longbussum)
        self.Btn_Exit.clicked.connect(longbussum.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(longbussum)

    def retranslateUi(self, longbussum):
        _translate = QtCore.QCoreApplication.translate
        longbussum.setWindowTitle(_translate("longbussum", "Massage Box"))
        self.label_11.setText(_translate("longbussum", "LongBusinessSummary"))
        self.Btn_Exit.setText(_translate("longbussum", "Exit"))
