# Form implementation generated from reading ui file 'd:\Python\Stock_py\Ui_File\prof_pf.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Profo_info(object):
    def setupUi(self, Profo_info):
        Profo_info.setObjectName("Profo_info")
        Profo_info.resize(886, 707)
        Profo_info.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Profo_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Profo_info)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 866, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tach_vale_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.tach_vale_label.setText("")
        self.tach_vale_label.setObjectName("tach_vale_label")
        self.verticalLayout_2.addWidget(self.tach_vale_label)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Positions_tableView = QtWidgets.QTableView(parent=self.scrollAreaWidgetContents)
        self.Positions_tableView.setObjectName("Positions_tableView")
        self.verticalLayout_2.addWidget(self.Positions_tableView)
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Transactions_tableView = QtWidgets.QTableView(parent=self.scrollAreaWidgetContents)
        self.Transactions_tableView.setObjectName("Transactions_tableView")
        self.verticalLayout_2.addWidget(self.Transactions_tableView)
        self.profo_csv = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.profo_csv.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.profo_csv.setObjectName("profo_csv")
        self.verticalLayout_2.addWidget(self.profo_csv)
        self.prof_close = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.prof_close.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.prof_close.setObjectName("prof_close")
        self.verticalLayout_2.addWidget(self.prof_close)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Profo_info)
        self.prof_close.clicked.connect(Profo_info.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Profo_info)

    def retranslateUi(self, Profo_info):
        _translate = QtCore.QCoreApplication.translate
        Profo_info.setWindowTitle(_translate("Profo_info", "Profo infomation"))
        self.label_2.setText(_translate("Profo_info", "Positions"))
        self.label_3.setText(_translate("Profo_info", "Transactions"))
        self.profo_csv.setText(_translate("Profo_info", "Download CSV"))
        self.prof_close.setText(_translate("Profo_info", "Close"))
