# Form implementation generated from reading ui file 'd:\Python\Stock_py\Ui_File\entrymanagement.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EntryManagement(object):
    def setupUi(self, EntryManagement):
        EntryManagement.setObjectName("EntryManagement")
        EntryManagement.resize(1000, 630)
        EntryManagement.setMinimumSize(QtCore.QSize(1000, 630))
        EntryManagement.setMaximumSize(QtCore.QSize(1000, 630))
        EntryManagement.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"border-color: rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EntryManagement)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_38 = QtWidgets.QLabel(parent=EntryManagement)
        self.label_38.setMinimumSize(QtCore.QSize(200, 25))
        self.label_38.setMaximumSize(QtCore.QSize(100, 25))
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.label_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout.addWidget(self.label_38)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EntrytoollistWidget = QtWidgets.QListWidget(parent=EntryManagement)
        self.EntrytoollistWidget.setMaximumSize(QtCore.QSize(470, 16777215))
        self.EntrytoollistWidget.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"border-color: rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);")
        self.EntrytoollistWidget.setObjectName("EntrytoollistWidget")
        self.horizontalLayout_2.addWidget(self.EntrytoollistWidget)
        self.widget = QtWidgets.QWidget(parent=EntryManagement)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.EntrygroupverticalLayout = QtWidgets.QVBoxLayout()
        self.EntrygroupverticalLayout.setObjectName("EntrygroupverticalLayout")
        self.verticalLayout_3.addLayout(self.EntrygroupverticalLayout)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Btn_Entrymm_reset = QtWidgets.QPushButton(parent=EntryManagement)
        self.Btn_Entrymm_reset.setMinimumSize(QtCore.QSize(100, 25))
        self.Btn_Entrymm_reset.setMaximumSize(QtCore.QSize(1000, 25))
        self.Btn_Entrymm_reset.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.Btn_Entrymm_reset.setObjectName("Btn_Entrymm_reset")
        self.horizontalLayout_4.addWidget(self.Btn_Entrymm_reset)
        self.Btn_Entrymm_enter = QtWidgets.QPushButton(parent=EntryManagement)
        self.Btn_Entrymm_enter.setMinimumSize(QtCore.QSize(100, 25))
        self.Btn_Entrymm_enter.setMaximumSize(QtCore.QSize(1000, 25))
        self.Btn_Entrymm_enter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.Btn_Entrymm_enter.setObjectName("Btn_Entrymm_enter")
        self.horizontalLayout_4.addWidget(self.Btn_Entrymm_enter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(EntryManagement)
        QtCore.QMetaObject.connectSlotsByName(EntryManagement)

    def retranslateUi(self, EntryManagement):
        _translate = QtCore.QCoreApplication.translate
        EntryManagement.setWindowTitle(_translate("EntryManagement", "Select Entry Managementl For Analysis"))
        self.label_38.setText(_translate("EntryManagement", "Select Entry Method"))
        self.Btn_Entrymm_reset.setText(_translate("EntryManagement", "RESET"))
        self.Btn_Entrymm_enter.setText(_translate("EntryManagement", " Enter to Quit the application"))
