# Form implementation generated from reading ui file 'd:\Python\Stock_py\Ui_File\ib_setting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ib_setting(object):
    def setupUi(self, ib_setting):
        ib_setting.setObjectName("ib_setting")
        ib_setting.resize(815, 331)
        ib_setting.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(ib_setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=ib_setting)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 795, 311))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(100, 25))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.IB_API_textedit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.IB_API_textedit.setMinimumSize(QtCore.QSize(0, 25))
        self.IB_API_textedit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.IB_API_textedit.setObjectName("IB_API_textedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.IB_API_textedit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tach_vale_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.tach_vale_label.setText("")
        self.tach_vale_label.setObjectName("tach_vale_label")
        self.verticalLayout_2.addWidget(self.tach_vale_label)
        self.IB_SAVE = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.IB_SAVE.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.IB_SAVE.setObjectName("IB_SAVE")
        self.verticalLayout_2.addWidget(self.IB_SAVE)
        self.IB_close = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.IB_close.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 69, 85);")
        self.IB_close.setObjectName("IB_close")
        self.verticalLayout_2.addWidget(self.IB_close)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ib_setting)
        self.IB_close.clicked.connect(ib_setting.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ib_setting)

    def retranslateUi(self, ib_setting):
        _translate = QtCore.QCoreApplication.translate
        ib_setting.setWindowTitle(_translate("ib_setting", "Interactive Brokers Setting"))
        self.label.setText(_translate("ib_setting", "API"))
        self.IB_SAVE.setText(_translate("ib_setting", "Save"))
        self.IB_close.setText(_translate("ib_setting", "Close"))
